### ISSUE TITLE
Rename password prompt in shell

### ISSUE THREAD

**Issue by dkulkarni** [redbubble/yak#64] opened 2018-05-25 04:23 UTC
Rename `password:` to `Okta password:` in the password prompt for Okta.
This just helps keep things less ambiguous

**Comment by rbvigilante** [comment] 2018-05-25 04:26
We actually already fixed this in https://github.com/redbubble/yak/pull/59; we just haven't made a release with this change in it yet.

**Comment by lucaswilric** [comment] 2018-05-25 04:26
Thanks @dkulkarni. This is a duplicate of #59, which is still waiting for release.

**Closed** 2018-05-25 04:26 UTC
Labels: enhancement
